### ISSUE TITLE
[Request] Remove or customize the [Server] part of the messages.

### ISSUE THREAD

**Issue by lnxredir** [Simplexity-Development/SimpleScheduledMessages#1]
Hi! I love your plugin and it works wonderfully, I just wish I could disable or customize the [Server] part of the messages, a simple customization would be enough! Cheers!

**Comment by RhythmicSys** [comment]
You should be able to do this already in the locale, there's an option `inserts.message-prefix` 

If this isn't working, let me know

**Comment by lnxredir** [comment]
Thanks! ill give that a try.

**Comment by RhythmicSys** [comment]
Assuming that the locale worked, if it didn't please open another issue! Closing for now
